# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wtw < Formula
  desc "TUI tool for managing git worktrees"
  homepage "https://github.com/krystxf/worktree-workflow"
  version "0.1.2-alpha"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/krystxf/worktree-workflow/releases/download/v0.1.2-alpha/worktree-workflow_darwin_arm64.tar.gz"
      sha256 "473b7387fc4d74faa4422cee53a38ebb47b6ecb72c3972e83e2055ddabcd5f7b"

      define_method(:install) do
        bin.install "wtw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/krystxf/worktree-workflow/releases/download/v0.1.2-alpha/worktree-workflow_linux_amd64.tar.gz"
      sha256 "d816e36f7a4beefc14a4c05731cf1442de8804cd41d52027368345f83ea5591d"
      define_method(:install) do
        bin.install "wtw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/krystxf/worktree-workflow/releases/download/v0.1.2-alpha/worktree-workflow_linux_arm64.tar.gz"
      sha256 "6f257758fe2a38bb08cb4a3e5bf0659460440981753d372423690711b72ac430"
      define_method(:install) do
        bin.install "wtw"
      end
    end
  end
end
