# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wtw < Formula
  desc "TUI tool for managing git worktrees"
  homepage "https://github.com/krystxf/worktree-workflow"
  version "0.2.7-alpha"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/krystxf/worktree-workflow/releases/download/v0.2.7-alpha/worktree-workflow_darwin_arm64.tar.gz"
      sha256 "6c2de6c4d00dccde4f51bf043de4c3de091ee18d63192c034bbc7e1604a5f2c5"

      define_method(:install) do
        bin.install "wtw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/krystxf/worktree-workflow/releases/download/v0.2.7-alpha/worktree-workflow_linux_amd64.tar.gz"
      sha256 "20b0f192141cbe37547aa5834d61e4028d7c7c55e8a9aaf2966877b66039ceb8"
      define_method(:install) do
        bin.install "wtw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/krystxf/worktree-workflow/releases/download/v0.2.7-alpha/worktree-workflow_linux_arm64.tar.gz"
      sha256 "04373332dc48c55282908ac24511aea2070adad34351f9a5e4a7b23906489760"
      define_method(:install) do
        bin.install "wtw"
      end
    end
  end
end
